# Generated by Django 5.2 on 2025-05-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscriptions_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
